org:
  neo4j:
    driver:
      uri: <uri>
      authentication:
        username: <username>
        password: <password>
      config:
        encrypted: false
database: <database>
spring:
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
