org :
  neo4j :
    driver :
      uri : neo4j+s://c1463b25.databases.neo4j.io
      authentication :
        username : neo4j
        password : _ILpJujYUrlGQDc-aJiASNqhidUgseJFhPmyl1-UOEE
      config :
        encrypted : true
database : neo4j
spring :
  graphql :
    schema :
      printer :
        enabled : true
    graphiql :
      enabled : true
