org:
  neo4j:
    driver:
      uri: neo4j://localhost
      authentication:
        username: neo4j
        password: movies
      config:
        encrypted: false
database: neo4j
dataPath: C:/Users/rebal/Documents/Pipeline/pipeline.json
spring:
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
